spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone:
        http://localhost:8761/eureka
management:
  health:
    circuitbreakers:
      enabled: true


 
resilience4j:
  circuitbreaker:
    instances:
      inventory:
      registerHealthIndicator: true
      eventConsumerBufferSize: 10
      slidingWindowSize: 5
      failureRateThreshold: 30
      waitDurationInOpenState: 5s
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true